appstore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from apps import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'accounts/',include('users.urls')),
    path(r'',          views.apps_default, name='default-page'),
    path(r'apps/',       include('apps.urls')),
    #re_path(r'apps/<slug:>/,       include('apps.urls')),
    path(r'search',      include('haystack.urls')),
    path(r'download/',   include('download.urls')),
    path(r'submit_app/', include('submit_app.urls')),
    path(r'users/',      include('users.urls')),
    path(r'help/',       include('help.urls')),
    path(r'backend/',    include('backend.urls')),
    path(r'obr/', include('obr.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# see https://docs.djangoproject.com/en/2.1/howto/static-files/

obr/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('pending_releases/repository.xml', views.serve_file_pending),
    path('releases/repository.xml', views.serve_file_released),
]

apps/models.py
import re
import hashlib
from shutil import rmtree
import subprocess
from os import mkdir, devnull
import os.path
from os.path import join as pathjoin
from urllib.parse import urljoin
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
#from django.core.urlresolvers import reverse
from django.urls import reverse

class Author(models.Model):
	name        = models.CharField(max_length=255)
	institution = models.CharField(max_length=255, null=True, blank=True)

	search_schema = ('name', 'institution')
	search_key = 'id'

	def __unicode__(self):
		if not self.institution:
			return self.name
		else:
			return self.name + ' (' + self.institution + ')'

_TagCountCache = dict()

class Tag(models.Model):
	name     = models.CharField(max_length=255, unique=True)
	fullname = models.CharField(max_length=255)

	@property
	def count(self):
		global _TagCountCache
		if self.name in _TagCountCache:
			count = _TagCountCache[self.name]
		else:
			count = App.objects.filter(active = True, tags = self).count()
			_TagCountCache[self.name] = count
		return count

	search_schema = ('fullname', )
	search_key = 'name'

	def __unicode__(self):
		return self.name
	class Meta:
		ordering = ["name"]

GENERIC_ICON_URL = urljoin(settings.STATIC_URL, 'apps/img/app_icon_generic.png')

def app_icon_path(app, filename):
    return filename

class App(models.Model):
    name         = models.CharField(max_length=127, unique=True)
    fullname     = models.CharField(max_length=127, unique=True)
    symbolicname = models.CharField(max_length=127, unique=True)
    description  = models.CharField(max_length=255, blank=True, null=True)
    details      = models.TextField(blank=True, null=True)
    import_packages = models.TextField(blank=True, null=True)
    manifest_version = models.CharField(max_length=31)
    lastmodified = models.CharField(max_length=127)
    version       = models.TextField(blank=False)
    tags         = models.ManyToManyField(Tag, blank=True)

    icon         = models.ImageField(blank=True, null=True)

    authors      = models.ManyToManyField(Author, blank=True, through='OrderedAuthor')
    editors      = models.ManyToManyField(User, blank=True)

    latest_release_date       = models.DateField(blank=True, null=True)
    has_releases              = models.BooleanField(default=False)

    license_text    = models.URLField(blank=True, null=True)
    license_confirm = models.BooleanField(default=False)

    website      = models.URLField(blank=True, null=True)
    tutorial     = models.URLField(blank=True, null=True)
    citation     = models.CharField(max_length=31, blank=True, null=True)
    coderepo     = models.URLField(blank=True, null=True)
    automation   = models.URLField(blank=True, null=True)
    contact      = models.EmailField(blank=True, null=True)

    stars        = models.PositiveIntegerField(default=0)
    votes        = models.PositiveIntegerField(default=0)
    downloads    = models.PositiveIntegerField(default=0)

    featured = models.BooleanField(default=False)

    active = models.BooleanField(default=False)

    def is_editor(self, user):
        if not user:
            return False
        if user.is_staff or user.is_superuser:
            return True
        return user in self.editors.all()

    def __str__(self):
        return self.fullname

    @property
    def stars_percentage(self):
        return 100 * self.stars / self.votes / 5 if self.votes != 0 else 0

    @property
    def icon_url(self):
        return self.icon.url if self.icon else GENERIC_ICON_URL

    @property
    def releases(self):
        return self.release_set.filter(active=True).all()

    def update_has_releases(self):
        self.has_releases = (self.release_set.filter(active=True).count() > 0)
        self.save()

    @property
    def page_url(self):
        return reverse('app_page', args=[self.name])

    @property
    def ordered_authors(self):
        return (a.author for a in OrderedAuthor.objects.filter(app = self))

    search_schema = ('^fullname', 'description', 'details')
    search_key = 'name'

    def __unicode__(self):
        return self.name

class OrderedAuthor(models.Model):
    author       = models.ForeignKey(Author,on_delete=models.CASCADE)
    app          = models.ForeignKey(App,on_delete=models.CASCADE)
    author_order = models.PositiveSmallIntegerField(default = 0)

    def __unicode__(self):
        return unicode(self.author_order) + ': ' + self.app.name + ' by ' + self.author.name

    class Meta:
        ordering = ["author_order"]

VersionRE = re.compile(r'^(\d+)(?:\.(\d)+)?(?:\.(\d)+)?(?:\.([\w-]+))?$')

def release_file_path(release, filename):
    return pathjoin(release.app.name, 'releases', release.version, filename)

class Release(models.Model):
    app           = models.ForeignKey(App,on_delete=models.CASCADE)
    version       = models.CharField(max_length=31)
    works_with    = models.CharField(max_length=31)
    notes         = models.TextField(blank=True, null=True)
    created       = models.DateTimeField(auto_now_add=True)
    active        = models.BooleanField(default=True)

    release_file  = models.FileField(upload_to=release_file_path)
    hexchecksum   = models.CharField(max_length=511, blank=True, null=True)
    dependencies  = models.ManyToManyField('self', related_name='dependents', symmetrical=False)

    @property
    def version_tuple(self):
        matched = VersionRE.match(self.version)
        if not matched:
            return None
        (major, minor, patch, tag) = matched.groups()
        major = int(major)
        minor = int(minor) if minor else None
        patch = int(patch) if patch else None
        return (major, minor, patch, tag)

    @property
    def created_iso(self):
        return self.created.isoformat()

    @property
    def release_file_url(self):
        return self.release_file.url if self.release_file else None

    @property
    def release_download_url(self):
        return reverse('release_download', args=[self.app.name, self.version])

    def __unicode__(self):
        return self.app.fullname + ' ' + self.version

    def calc_checksum(self):
        cs = hashlib.sha512()
        f = self.release_file.file
        f.open('rb')
        while True:
            buf = f.read(128)
            if not buf: break
            cs.update(buf)
        f.close()
        self.hexchecksum = '%s:%s' % (cs.name, cs.hexdigest())
        self.save()

    def delete_files(self):
        self.release_file.delete()
        if self.releaseapi_set.count() > 0:
            api = self.releaseapi_set.get()
            api.delete_files()
            api.delete()

    class Meta:
        ordering = ['-created']

def screenshot_path(screenshot, filename):
    return pathjoin(screenshot.app.name, 'screenshots', filename)

def thumbnail_path(screenshot, filename):
    return pathjoin(screenshot.app.name, 'thumbnails', filename)

class Screenshot(models.Model):
    app        = models.ForeignKey(App,on_delete=models.CASCADE)
    screenshot = models.ImageField(upload_to=screenshot_path)
    thumbnail  = models.ImageField(upload_to=thumbnail_path)

    def __unicode__(self):
        return '%s - %d' % (self.app.fullname, self.id)

def javadocs_path(release_api, filename):
    return pathjoin(release_api.release.app.name, 'releases', release_api.release.version, filename)

def pom_xml_path(release_api, filename):
    return pathjoin(release_api.release.app.name, 'releases', release_api.release.version, filename)

class ReleaseAPI(models.Model):
    release           = models.ForeignKey(Release,on_delete=models.CASCADE)
    javadocs_jar_file = models.FileField(upload_to=javadocs_path)
    pom_xml_file      = models.FileField(upload_to=pom_xml_path)

    def __unicode__(self):
        return unicode(self.release)

    def extract_javadocs_jar(self):
        file = self.javadocs_jar_file
        dirpath = file.path + '-extracted'
        if not os.path.exists(dirpath):
            mkdir(dirpath)
        nullfile = open(devnull, 'w')
        subprocess.call(['unzip', file.path, '-d', dirpath], stdout = nullfile, stderr = nullfile)
        nullfile.close()

    def delete_files(self):
        dirpath = self.javadocs_jar_file.path + '-extracted'
        if os.path.exists(dirpath):
            rmtree(dirpath)
        self.javadocs_jar_file.delete()
        self.pom_xml_file.delete()

apps/templates/all_apps.html
{% extends "nav_panel.html" %}
{% load static %}
{% load app_buttons %}

{% block title %}
 - All Apps
{% endblock %}

{% block main %}
  {% list_of_apps apps %}
{% endblock %}

apps/templates/app_button.html
{% load static %}

<div class="app_button"
  order_index="{{ order_index }}"
  fullname="{{ app.fullname }}"
  votes="{{ app.votes }}"
  downloads="{{ app.downloads }}"
  latest_release_date="{{ app.latest_release_date.isoformat }}"
  onClick="window.location='{% url 'app_page' app.name %}';">


  <a href="{% url 'app_page' app.name %}">
    <div class="partial">
      <table border="0" width="100%">
        <tr valign="top">
          <td width="64" rowspan="2">
            <div class="app_icon">
              <img src="{{ app.icon_url }}"/>
            </div>
          </td>
          <td align="left">
            <h5>{{ app.fullname }}</h5>
          </td>
          <td valign="baseline">
            <div class="stars">
              <i class="stars-empty icon-stars-empty"></i>
              <i class="stars-full icon-stars-filled" style="width: {{ app.stars_percentage }}%"></i>
            </div>
          </td>
        </tr>
        <tr valign="top">
          <td valign="top">
            <div class="description">
              {% if app.description %}
                {{ app.description }}
              {% endif %}
            </div>
          </td>
        </tr>
      </table>
    </div>

    <div class="full">
      <table border="0" width="100%">
        <tr valign="top">
          <td width="64" rowspan="2">
            <div class="app_icon">
              <img src="{{ app.icon_url }}"/>
            </div>
          </td>
          <td align="left">
            <h5>{{ app.fullname }}</h5>
          </td>
          <td valign="baseline">
            <div class="stars">
              <i class="stars-empty icon-stars-empty"></i>
              <i class="stars-full icon-stars-filled" style="width: {{ app.stars_percentage }}%"></i>
            </div>
          </td>
        </tr>
        <tr valign="top">
          <td>
            <div class="description">
              {% if app.description %}
                {{ app.description }}
              {% endif %}
            </div>
          </td>
        </tr>
      </table>
    </div>
  </a>
</div>

apps/templates/app_buttons.html
{% load app_buttons %}

{% for app in apps %}
  {% if forloop.counter|divisibleby:2 %}
    <div class="span5" id="right">
      {% app_button app forloop.counter %}
    </div>
  {% endif %}

  {% if not forloop.counter|divisibleby:2 %}
    <div class="span5" id="left">
      {% app_button app forloop.counter %}
    </div>
  {% endif %}
{% endfor %}

apps/templates/app_page.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{%import logging

# Get an instance of a logger
logger = logging.getLogger("app_page.html") %}

{% block more_head %}
<link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_page.css" />
<link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_stars.css" />
<script type="text/javascript" src="{% get_static_prefix %}common/lib/js/jquery.timeago.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/lib/js/Markdown.Converter.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/lib/js/Markdown.Sanitizer.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/js/setup_ajax_for_csrf.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/js/markdown_util.js"></script>
{% endblock %}

{% block title %}- {{ app.fullname }}{% endblock %}

{% block content %}
{% csrf_token %}

{# "Go back to" link #}
{% if go_back_to_title %}
<div class="row">
	<div class="span8" style="margin-bottom: 2em;">
		<a href="{{ go_back_to_url }}">&larr; Go back to {% autoescape off %}{{ go_back_to_title }}{% endautoescape %}</a>
	</div>
</div>
{% endif %}

{# App header #}
<div class="row">
	{# App icon #}
	<div class="span1" style="line-height: 64px;">
		<img style="vertical-align: middle;" src="{{ app.icon_url }}"/>
	</div>
	{# App name and description #}
	<div class="span7">
		<h2 id="app-name">
			{{ app.fullname }}
		</h2>
		{% if app.description %}<b>{{ app.description }}</b>{% endif %}
	</div>

	{# Editor menu #}
	{% if is_editor %}
	<div class="span3 offset1">
		<div class="btn-group pull-right">
			<a class="btn btn-warning dropdown-toggle" data-toggle="dropdown" href="#">
				<i class="icon-pencil icon-white"></i>
				Editor Actions
				<span class="caret"></span>
			</a>
			<ul class="dropdown-menu pull-right">
				<li><a href="{% url 'app_page_edit' app.name %}">Edit this page</a></li>
				<li><a href="{% url 'submit-app' %}?expect_app_name={{ app.fullname }}">Submit a 3.0 app release</a></li>
				<li class="divider"></li>
				<li><a data-toggle="modal" href="#delete_ratings_modal">Delete all ratings</a></li>
			</ul>
		</div>
	</div>
	{% endif %}
	{# End editor menu #}
</div>
{# End app header #}

{# App usage info (ratings, downloads, helpdesk, citations, discussions) #}
<div class="row">
	<div class="span12" id="app-usage-info">
		{# Ratings #}
		<div class="rating-stars" data-placement="bottom" data-title="Rate this app! <a class='close' style='margin-left: 0.5em;'>&times;</a>" data-html="true">
			<i class="rating-stars-empty icon-stars-empty"></i>
			<i class="rating-stars-filled icon-stars-filled" style="width: {{ app.stars_percentage|escapejs }}%;"></i>
			<span class="rating-spacer"></span>
		</div>
		<span id="rating-count">({{ app.votes|escapejs }})</span>
		{# End Ratings #}

		{# Downloads #}
		{% if app.has_releases %}
		<span class="app-usage-info-divider"></span>
		<a href="{% url 'app_stats' app.name %}" target="_blank" class="has-tooltip" data-toggle="tooltip" data-title="Click to view the download stats.">
			{{ app.downloads }} downloads
		</a>
		{% endif %}
		{# End Downloads #}

		{# Helpdesk #}
		<a> | </a>
		<a href="https://groups.google.com/forum/?fromgroups#!searchin/integrated-genome-browser-help-desk/{{ app.fullname }}" target="_blank" class="has-tooltip" data-toggle="tooltip" data-title="Search IGB Helpdesk for questions about this app.">helpdesk</a>
		{# End Helpdesk #}

		{# Citations #}
		{% if app.citation %}
		<a> | </a>
		<a href="https://www.ncbi.nlm.nih.gov/pubmed?linkname=pubmed_pubmed_citedin&from_uid={{ app.citation }}" target="_blank" class="has-tooltip" data-toggle="tooltip" data-title="Search PubMed for articles citing this app.">{% trans "  citations" %}</a>

		{% endif %}
		{# End Citations #}
		<span class="app-usage-info-divider"></span>

<!--		{# badges #}-->
<!--		{% if app.has_releases %}-->
<!--		<img src="{% get_static_prefix %}apps/img/sticker.png" class="has-tooltip" data-toggle="tooltip" data-title="This app is available for IGB.">-->
<!--		{% endif %}-->


		{% if app.coderepo %}
		<a href="{{ app.coderepo }}" target="_blank">
			<img src="{% get_static_prefix %}apps/img/open-source.png" class="has-tooltip" data-toggle="tooltip" data-title="This app is open source.">
		</a>
		{% endif %}
		{% if 'www' in app.automation %}
		<a href="https://{{ app.automation }}" target="_blank">
			<img src="{% get_static_prefix %}apps/img/automation.png" class="has-tooltip" data-toggle="tooltip" data-title="This app supports automation.">
		</a>
		{% endif %}
		{# end badges #}
	</div>
</div>
{# End app usage info #}

{# Main app page content #}
<div class="row">
	<div class="span8">
		{# Tabs #}
		<ul id="app-info-tabs" class="nav nav-tabs">
			<li class="active">
				<a href="#app-details-tab" data-toggle="tab">
					<b>Details</b>
				</a>
			</li>
			{% if app.has_releases %}
			<li>
				<a href="#app-releases-tab" data-toggle="tab">
					<b>Release History</b>
				</a>
			</li>
			{% endif %}
		</ul>
		{# End Tabs #}

		{# Tab content #}
		<div class="tab-content">
			{# Details tab #}
			<div class="tab-pane active" id="app-details-tab">
				{# Categories #}
				{% if app.tags.all %}
				<div class="row">
					<div class="span8">
						Categories:
						{% for tag in app.tags.all %}
						<a class="link" href="{% url 'tag_page' tag.name %}">{{ tag.fullname }}</a>{% if not forloop.last %}, {% endif %}
						{% endfor %}
					</div>
				</div>
				{% endif %}
				{# End Categories #}

				{# Screenshots #}
				{% if app.screenshot_set.all %}
				<div class="row">
					<div class="span8" id="app-screenshots">
						{% for screenshot in app.screenshot_set.all %}
						<a href="{{ screenshot.screenshot.url }}" target="_blank">
							<img src="{{ screenshot.thumbnail.url }}"/>
						</a>
						{% endfor %}
					</div>
				</div>
				{% endif %}
				{# End Screenshots #}

				{# Details #}
				{% if decoded_details %}
				<div class="row">
					<div class="span8" id="app-details-md">{{ decoded_details }}</div>
				</div>
				{% endif %}
				{# End Details #}

				{# Authors #}
				{% if app.authors.all %}
				<div class="row">
					<div class="span8">
						Authors:
						<ul>
							{% for author in app.ordered_authors %}
							<li>
								<a href="{% url 'author_page' author.name %}">
									{{ author.name }} {% if author.institution %} ({{ author.institution }}){% endif %}
								</a>
							</li>
							{% endfor %}
						</ul>
					</div>
				</div>
				{% endif %}
				{# End Authors #}
			</div>
			{# End Details tab #}

			{# Releases tab #}
			{% if app.has_releases %}
			<div class="tab-pane" id="app-releases-tab">
				{% for release in app.releases %}
				<div class="row">
					<div class="span8">
						{# Release version #}
						<h4>
							<!-- Removed release.version argument -->
							<a href="{% url 'release_download' app.name %}">
								{{ release.version }}
							</a>
							<small><abbr class="timeago" title="{{ release.created_iso }}"></abbr></small>
						</h4>
						{# End Release version #}

						{# Works with #}
						<p>
							<strong>Works with</strong> IGB
							{{ release.works_with }}
						</p>
						{# End Works with #}

						{# Release #}
						{% if release.releaseapi_set.count %}
						{% with releaseapi=release.releaseapi_set.get %}
						<p>
							<strong>API</strong>
							&nbsp;
							<a target="_blank" href="{{ releaseapi.pom_xml_file.url }}">pom.xml</a>
							&nbsp;
							<a target="_blank" href="{{ releaseapi.javadocs_jar_file.url }}-extracted">Javadocs</a>
						</p>
						{% endwith %}
						{% endif %}

						{# Release dependencies #}
						{% if release.dependents.count %}
						<p>
							<strong>Apps that depend on this release</strong>
							<ul>
								{% for dependent in release.dependents.all %}
								<li><a href="{% url 'app_page' dependent.app.name %}" target="_blank">{{ dependent.app.fullname }}</a> {{ dependent.version }}</li>
								{% endfor %}
							</ul>
						</p>
						{% endif %}
						{# End Release dependencies #}

						{% if release.notes %}
						<p><strong>Release Notes</strong></p>
						<div class="app-release-notes">{{ release.notes }}</div>
						{% endif %}
						{# End Release #}
						<hr>
					</div>
				</div>
				{% endfor %} {# end looping thru each release #}
			</div>
			{% endif %}
			{# End Releases tab #}
		</div>
	</div>
	{# End Tab content #}

	{# Right-hand panels #}
	<div class="span3 offset1">

		{# 3.0 download panel #}
		<div class="well" id="app_status_block">
			<h6 class="panel-title muted">IGB</h6>
			<button class="btn btn-large btn-block" id="app-install-btn">
				<i></i> {# <-- download button icon will go here #}
				<h4></h4> {# <-- download button text will go here #}
			</button>
			<p id="app_version"></p>
			{% if app.license_text %}<p><strong>License</strong> <a href="{{ app.license_text }}" target="_blank">Click here</a></p>Download Stats{% endif %}
			<p><strong>Works with</strong> <a href="https://bioviz.org/" target="_blank" id="igb_version"></a></p>
			<p><strong>Download Stats</strong> <a href="{% url 'app_stats' app.name %}" target="_blank">Click here</a></p>
		</div>

		{# end 3.0 download panel #}

		{# app resources #}
		<div class="alert">
			<ul class="nav nav-list">
			<!li class="nav-header">

			<h5>		<!i class="fa fa-circle-o-notch fa-spin" style="font-size:16px"><!/i>&ensp; RESOURCES</font> </h5>
			<!/li>

				<li><a href="https://groups.google.com/forum/#!forum/integrated-genome-browser-help-desk" target="_blank">
					<i class="icon-question-sign"></i>
					Ask a question
				</a></li>

				<li><a href="https://groups.google.com/forum/?fromgroups#!searchin/integrated-genome-browser-help-desk/{{ app.fullname }}" target="_blank">
					<i class="icon-comment"></i>
					Search helpdesk
				</a></li>
				<li class="divider"></li>

				{% if app.website %}
				<li><a href="{{ app.website }}" target="_blank">
					<i class="icon-home"></i> Website
				</a></li>
				{% endif %}

				{% if app.tutorial %}
				<li><a href="{{ app.tutorial }}" target="_blank">
					<i class="icon-book"></i> Tutorial
				</a></li>
				{% endif %}

				{% if app.citation %}
				<li><a href="http://www.ncbi.nlm.nih.gov/pubmed/{{ app.citation }}" target="_blank">
					<i class="icon-heart"></i> Cite this App
				</a></li>
				{% endif %}

				{% if app.coderepo %}
				<li><a href="{{ app.coderepo }}" target="_blank">
					<i class="icon-list-alt"></i> Code Repository
				</a></li>
				{% endif %}
				<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
				{% if 'www' in app.automation %}
				<li><a href="http://{{app.automation}}" target="_blank">

						<i class="fa fa-gear fa-spin" style="color:black"></i>
 Automation Support
				</a></li>
				{% endif %}

				{% if app.contact %}
				<li><a href="mailto:{{ app.contact }}" target="_blank">
					<i class="icon-envelope"></i> E-mail
				</a></li>
				{% endif %}
			</ul>
		</div>
		{# end app resources #}
	</div>
	{# end right-hand panels #}
</div>
{# end main app page content #}

{# Delete all ratings modal dialog #}
<div class="modal hide fade in" id="delete_ratings_modal">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">&times;</a>
		<h3>Delete All Ratings</h3>
	</div>
	<div class="modal-body">
		Are you sure you want to delete all of your app's ratings?
	</div>
	<div class="modal-footer">
		<form target="" method="post" style="margin: 0;">
			{% csrf_token %}
			<input type="hidden" name="action" value="ratings_delete_all">
			<a href="#" class="btn" data-dismiss="modal">Cancel</a>
			<input type="submit" class="btn btn-danger" value="Yes, I'm Sure">
		</form>
	</div>
</div>
{# End modal dialog #}

{# License modal dialog #}
{% if app.license_confirm and app.license_text %}
<div class="modal hide fade in" id="license_modal">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">&times;</a>
		<h3>License Agreement</h3>
	</div>
	<div class="modal-body">
		<iframe data-src="{{ app.license_text }}" width="500" height="400"></iframe>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Don't Accept</a>
		<a href="#" class="btn btn-primary">Accept</a>
	</div>
</div>
{% endif %}
{# End license modal dialog #}

{# Vote popover content #}
<script type="text/html" id="rate-popover-content">
<div class="rating-stars">
	<i class="rating-stars-empty icon-stars-empty"></i>
	<i class="rating-stars-filled icon-stars-filled" style="width: 100%;"></i>
	<span class="rating-spacer"></span>
</div>
<button class="btn btn-mini" id="rate-btn">Rate it <span id="rating">5</span> star(s)</button>
</script>
{# End vote popover content #}

<script type="text/javascript" src="{% get_static_prefix %}apps/js/app_page.js"></script>

<script type="text/javascript">
$('.has-tooltip').tooltip();
AppPage.setup_install("{{ app.name|escapejs }}",
	"{{ app.symbolicname|escapejs }}");

{% if app.details %}
AppPage.setup_details();
{% endif %}

AppPage.setup_stars();

AppPage.setup_release_notes();
</script>
{% endblock %}

apps/templates/apps_default.html
{% extends "nav_panel.html" %}
{% load app_buttons %}

{% block main %}
  <style type="text/css">
    h2 { margin-bottom: 0.5em; }
    .span4 { margin-bottom: 1em; }
  </style>
  <div class="row span12">
    <div class="span12" style="text-align: right;">
      <a href="{% url 'submit-app' %}" class="btn btn-lg btn-success">Submit your app &raquo;</a>
    </div>
  </div>
<!--  <div class="row">{% app_buttons latest_apps %}</div>-->
<!--  <div class="row">-->
<!--    <div class="span8" style="text-align: right;">-->
<!--      <a href="{% url 'all_apps'%}#newest release">more newest releases &raquo;</a>-->
<!--    </div>-->
<!--  </div>-->

  <div class="row span12"><div class="span12"><h2>Community Favorites</h2></div></div>
  <div class="row span12">{% app_buttons downloaded_apps %}</div>
  <div class="row span12">
    <div class="span12" style="text-align: right;">
      <a href="{% url 'all_apps'%}#downloads">more community favorites &raquo;</a>
    </div>
  </div>

  <a style="display: none;" href="/media/fu.txt">fu skript kiddiez</a>
{% endblock %}

apps/templates/apps_with_tag.html
{% extends "nav_panel.html" %}
{% load app_buttons %}

{% block title %}
- {{ tag.fullname }} category
{% endblock %}

{% block main %}
  <div class="row" style="margin-bottom: 2em;">
    <div class="span12">
      <h1>{{ tag.fullname|capfirst }}</h1>
      <p>
      <a href='https://groups.google.com/forum/?fromgroups#!searchin/integrated-genome-browser-help-desk/"{{ tag.fullname }}"' target="_blank">
        <i class="icon-comment"></i>
        Search for posts about {{ tag.fullname }} &rarr;
      </a>
      </p>
      <p>
      <a href="https://groups.google.com/forum/?fromgroups#!newtopic/integrated-genome-browser-help-desk" target="_blank">
        <i class="icon-question-sign"></i>
        Ask a question about {{ tag.fullname }} &rarr;
      </a>
      </p>
    </div>
  </div>
  {% list_of_apps apps %}
{% endblock %}